import '@/assets/css/main.css';
import IconifySetup from '@/components/iconifySetup';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Bricolage_Grotesque, Inter } from 'next/font/google';

// const bricolageGrotesque = Bricolage_Grotesque({
//   variable: '--font-bricolage-grotesque',
//   subsets: ['latin']
// });
const mainFont = Inter({
  variable: '--font-sans',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.variable} font-sans antialiased`}>
        <IconifySetup />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
